name: ResourceRegions
main: me.dags.resourceregions.ResourceRegions
version: ${project.version}
author: dags_
softdepend: [WorldGuard]
website: ${project.url}

commands:
  resourceregion:
    aliases: [rr, rregion]
    description: Region command
    usage: /resourceregion
    permission-message: Ain't got perms fo' dat yo!
    permission: resourceregions.region
  rpurl:
    aliases: [rp]
    description: Set resourcepack url
    useage: /rp <name> <url>
    permission-message: Ain't got perms fo' dat yo!
    permission: resourceregions.rpurl